server:
  port: 8080
  servlet:
    context-path: /
spring:
  thymeleaf:
    cache: false
monitor:
  kafka:
    address: localhost:9092
  mysql:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
  es:
    address: localhost:9200